baseURL = 'https://infopa.netlify.app/'
languageCode = 'en-us'
title = 'Demand and Capacity Healthcare Model'
theme = 'PaperMod'

[params]
ShowCodeCopyButtons = true
ShowToc = true
ShowSidebar = true
ShowSidebarMenu = true

[[menu.main]]
  identifier = 'Model Inputs'
  name = 'Model Inputs'
  pageRef = 'ModelInputs.md'
  weight = 2

[[menu.main]]
  identifier = 'Model Outputs'
  name = 'Model Outputs'
  pageRef = 'ModelOutputs.md'
  weight = 3

[[menu.main]]
  identifier = 'Probabilistic'
  name = 'Probabilistic'
  pageRef = 'Probabilistic.md'
  weight = 4

[[menu.main]]
  identifier = 'Use Case Examples'
  name = 'Use Case Examples'
  pageRef = 'UseCase.md'
  weight = 5

[[menu.main]]
  identifier = 'Contact'
  name = 'Contact'
  url = 'mailto:mlcsu.su.datascience@nhs.net'
  weight = 6